# Generated by Django 6.0.7 on 2026-09-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['simplified'], name='learning_vo_simplif_9ba446_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['hsk_level'], name='learning_vo_hsk_lev_d2f69b_idx'),
        ),
    ]
